openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /api/auth/signup:
    post:
      tags:
        - auth-controller
      operationId: registerUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /api/auth/signin:
    post:
      tags:
        - auth-controller
      operationId: authenticateUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /api/test/user:
    get:
      tags:
        - test-controller
      operationId: userAccess
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /api/test/mod:
    get:
      tags:
        - test-controller
      operationId: moderatorAccess
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /api/test/all:
    get:
      tags:
        - test-controller
      operationId: allAccess
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /api/test/admin:
    get:
      tags:
        - test-controller
      operationId: adminAccess
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    SignupRequest:
      required:
        - email
        - password
        - username
      type: object
      properties:
        username:
          maxLength: 20
          minLength: 3
          type: string
        email:
          maxLength: 50
          minLength: 0
          type: string
        role:
          uniqueItems: true
          type: array
          items:
            type: string
        password:
          maxLength: 40
          minLength: 6
          type: string
    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
