CREATE TABLE roles
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(20),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    email    VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_74165e195b2f7b25de690d14a UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_77584fbe74cc86922be2a3560 UNIQUE (username);

CREATE TABLE subscriptions
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255),
    following VARCHAR(255),
    CONSTRAINT pk_subscriptions PRIMARY KEY (id)
);

ALTER TABLE subscriptions
    ADD CONSTRAINT uc_843766e2ce1daeb7799a177be UNIQUE (name);

ALTER TABLE subscriptions
    ADD CONSTRAINT uc_e19f2d68a9e6da414bbfd618d UNIQUE (id);

CREATE TABLE postinfo
(
    id      BIGINT NOT NULL,
    content VARCHAR(255),
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_postinfo PRIMARY KEY (id)
);

ALTER TABLE postinfo
    ADD CONSTRAINT FK_POSTINFO_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);